<!-- Affiliate program -->
<section class="affiliate_programm">
    <div class="container">
        <h2 class="text-center has_subtitle">GFLeads affiliate system guide</h2>
        <div class="section_subtitle text-center">Learn how to register, operate, and receive payments using our user-friendly system. Our guide helps you get started quickly and efficiently from <br>setting up your account to tracking your referrals and receiving payments,  ensures you have all the information you need at your fingertips.</div>

        <!-- programm tab -->
        <div class="affiliate_programm__tab tab">
            <div class="tab__content">
                <div class="content_item active" id="desctop">
                    <div class="affiliate_programm__tab--block">
                        <div class="affiliate_programm__tab--content_left">
                            <div class="pagination_block">
                                <div class="pagination_title">Step</div>
                                <div class="steps_pagination" data-slider="0"></div>
                            </div>
                            <div class="steps__block affilate">
                                <div class="steps__content step_content_main" data-slider="0">
                                    <div class="step__item active">
                                        <div class="step__title">Register in our program</div>
                                        <div class="step__description">Go to the registration page and fill it out with your information. Please enter a valid email address, as a confirmation code will be sent to it, which you will need to enter in the next form.
                                            <p>Go to the registration page and fill it out with your information. Please enter a valid email address, as a confirmation code will be sent to it, which you will need to enter in the next form.</p>
                                        </div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Starting work</div>
                                        <div class="step__description">After registration, you will receive a personal referral phone number and a referral link and various services will become available to you for promotion. 
                                            <p>Initially, you will gain access to «Public Adjuster Services». We will illustrate the system’s functionality using this service as an example.</p>
                                        </div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Statistic: tracking your work</div>
                                        <div class="step__description">In the «Statistic» section, you can monitor the traffic generated by your referral link or calls made to your referral phone number. 
                                            <p>If the offer does not meet our conditions, we will try to sell it for the maximum percentage. You will not receive the expected payout for this lead, but we will endeavor to provide you with the maximum possible reward for it.</p>
                                        </div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Payment to you</div>
                                        <div class="step__description">«Finances» - a section where you can immediately see the amount you have earned during the current month.
                                            <p>Payments are made twice a month, at the beginning and at the end of the month. If your lead came to us in the first half of the month (From the 1st to the 15th), then at the end of the second half of the month you will be able to see the replenishment on your balance. And the funds will be sent to the payment list. And you will be able to withdraw funds on the 15th of next month. Trusted, long-term customers enjoy enhanced payment terms.</p>
                                        </div>
                                    </div>
                                </div>
                                <div class="steps__action">
                                    <a href="https://v2.gfleads.com/publishers/auth/signin" class="btn btn-orange btn-lg approach">Start now</a>
                                </div>
                                <div class="steps__navigation" data-slider="0">
                                    <a href="#" class="nav_prev">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 44 44" fill="none">
                                            <circle cx="22" cy="22" r="22" transform="matrix(-1 0 0 1 44 0)" fill="#539DF5" />
                                            <path d="M20.636 30.4028C20.7924 30.5443 20.998 30.6191 21.2088 30.6113C21.4196 30.6034 21.619 30.5135 21.7645 30.3607C21.91 30.208 21.99 30.0044 21.9875 29.7934C21.985 29.5825 21.9002 29.3809 21.7511 29.2316L15.0098 22.8106L30.8995 22.8106C31.114 22.8106 31.3197 22.7254 31.4714 22.5737C31.6231 22.422 31.7083 22.2163 31.7083 22.0018C31.7083 21.7873 31.6231 21.5815 31.4714 21.4298C31.3197 21.2782 31.114 21.1929 30.8995 21.1929L15.0098 21.1929L21.7511 14.7709C21.9002 14.6216 21.985 14.42 21.9875 14.209C21.99 13.9981 21.91 13.7945 21.7645 13.6417C21.619 13.4889 21.4196 13.399 21.2088 13.3912C20.998 13.3833 20.7924 13.4582 20.636 13.5997L12.6341 21.221C12.4593 21.3874 12.3453 21.6077 12.3105 21.8465C12.292 21.9496 12.2923 22.0552 12.3116 22.1581C12.3467 22.3966 12.4606 22.6164 12.6351 22.7826L20.636 30.4028Z" fill="white" />
                                        </svg>
                                    </a>
                                    <a href="#" class="nav_next">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 44 44" fill="none">
                                            <circle cx="22" cy="22" r="22" fill="#539DF5" />
                                            <path d="M23.364 30.4028C23.2076 30.5443 23.002 30.6191 22.7912 30.6113C22.5804 30.6034 22.381 30.5135 22.2355 30.3607C22.09 30.208 22.01 30.0044 22.0125 29.7934C22.015 29.5825 22.0998 29.3809 22.2489 29.2316L28.9902 22.8106L13.1005 22.8106C12.886 22.8106 12.6803 22.7254 12.5286 22.5737C12.3769 22.422 12.2917 22.2163 12.2917 22.0018C12.2917 21.7873 12.3769 21.5815 12.5286 21.4298C12.6803 21.2782 12.886 21.1929 13.1005 21.1929L28.9902 21.1929L22.2489 14.7709C22.0998 14.6216 22.015 14.42 22.0125 14.209C22.01 13.9981 22.09 13.7945 22.2355 13.6417C22.381 13.4889 22.5804 13.399 22.7912 13.3912C23.002 13.3833 23.2076 13.4582 23.364 13.5997L31.3659 21.221C31.5407 21.3874 31.6547 21.6077 31.6895 21.8465C31.708 21.9496 31.7077 22.0552 31.6884 22.1581C31.6533 22.3966 31.5394 22.6164 31.3649 22.7826L23.364 30.4028Z" fill="white" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="affiliate_programm__tab--content_right">
                            <div class="swiper programm_slider" data-slider="0">
                                <div class="swiper-wrapper">

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/Step_1_publishers.png" alt="Transparent reporting">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <!-- <div class="swiper-slide">
                                        <div class="programm_image no_back">
                                            <div class="form-container">
                                                <h1>Website Integration Request Form</h1>
                                                <form>
                                                    <label for="full-name">Full name<span style="color: red;">*</span></label>
                                                    <input type="text" id="full-name" name="full-name"  required>

                                                    <label for="phone-number">Phone number<span style="color: red;">*</span></label>
                                                    <input type="tel" id="phone-number" name="phone-number"  required>

                                                    <label for="email">Email address<span style="color: red;">*</span></label>
                                                    <input type="email" id="email" name="email" required>

                                                    <label for="website-url">Website URL<span style="color: red;">*</span></label>
                                                    <input type="url" id="website-url" name="website-url"  required>

                                                    <label for="comments">Comments or questions</label>
                                                    <textarea id="comments" name="comments"></textarea>

                                                    <button type="submit">Submit request</button>
                                                </form>
                                                <p>By submitting this form, you agree with the <a href="#">Privacy Policy</a>.</p>
                                            </div>
                                        </div>
                                    </div> -->

                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/Step_2_pas_screen2-min.jpg" alt="Submitting lead data anonymously">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/Step_4_stat_screen-min.jpg" alt="Submitting lead data anonymously">
                                        </div>
                                    </div>

                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/Step_5_fin_screen-min.jpg" alt="Tracking and managing referrals">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="content_item" id="mobile">
                    <div class="affiliate_programm__tab--block">
                        <div class="affiliate_programm__tab--content_left">
                            <div class="pagination_block">
                                <div class="pagination_title">Step</div>
                                <div class="steps_pagination" data-slider="1"></div>
                            </div>
                            <div class="steps__block">
                                <div class="steps__content" data-slider="1">
                                    <div class="step__item active">
                                        <div class="step__title">Download & register the app</div>
                                        <div class="step__description">Download our mobile application from the Google Play or App Store. Register within the app or log in with your account using your email and password.</div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Starting work </div>
                                        <div class="step__description">You will receive a personal referral phone number and a referral link. Various services will become available to you for promotion.</div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Example work basics</div>
                                        <div class="step__description">If the person cannot call or click your link, you can navigate to the link by yourself and enter all the necessary information on their behalf. Just provide their name, address, and phone number in the form.</div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Statistic & tracking your work
                                        </div>
                                        <div class="step__description">Monitor the traffic generated by your referral link or calls made to your referral phone number.</div>
                                    </div>
                                    <div class="step__item">
                                        <div class="step__title">Payment to you</div>
                                        <div class="step__description">Get your payments twice a month, at the beginning and at the end of the month. You will be able to withdraw funds on the 15-th of next month.</div>
                                    </div>
                                </div>
                                <div class="steps__action">
                                    <a href="https://v2.gfleads.com/publishers/auth/signin" class="btn btn-orange btn-lg approach">Start now</a>
                                </div>
                                <div class="steps__navigation" data-slider="1">
                                    <a href="#" class="nav_prev">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 44 44" fill="none">
                                            <circle cx="22" cy="22" r="22" transform="matrix(-1 0 0 1 44 0)" fill="#539DF5" />
                                            <path d="M20.636 30.4028C20.7924 30.5443 20.998 30.6191 21.2088 30.6113C21.4196 30.6034 21.619 30.5135 21.7645 30.3607C21.91 30.208 21.99 30.0044 21.9875 29.7934C21.985 29.5825 21.9002 29.3809 21.7511 29.2316L15.0098 22.8106L30.8995 22.8106C31.114 22.8106 31.3197 22.7254 31.4714 22.5737C31.6231 22.422 31.7083 22.2163 31.7083 22.0018C31.7083 21.7873 31.6231 21.5815 31.4714 21.4298C31.3197 21.2782 31.114 21.1929 30.8995 21.1929L15.0098 21.1929L21.7511 14.7709C21.9002 14.6216 21.985 14.42 21.9875 14.209C21.99 13.9981 21.91 13.7945 21.7645 13.6417C21.619 13.4889 21.4196 13.399 21.2088 13.3912C20.998 13.3833 20.7924 13.4582 20.636 13.5997L12.6341 21.221C12.4593 21.3874 12.3453 21.6077 12.3105 21.8465C12.292 21.9496 12.2923 22.0552 12.3116 22.1581C12.3467 22.3966 12.4606 22.6164 12.6351 22.7826L20.636 30.4028Z" fill="white" />
                                        </svg>
                                    </a>
                                    <a href="#" class="nav_next">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="44" height="44" viewBox="0 0 44 44" fill="none">
                                            <circle cx="22" cy="22" r="22" fill="#539DF5" />
                                            <path d="M23.364 30.4028C23.2076 30.5443 23.002 30.6191 22.7912 30.6113C22.5804 30.6034 22.381 30.5135 22.2355 30.3607C22.09 30.208 22.01 30.0044 22.0125 29.7934C22.015 29.5825 22.0998 29.3809 22.2489 29.2316L28.9902 22.8106L13.1005 22.8106C12.886 22.8106 12.6803 22.7254 12.5286 22.5737C12.3769 22.422 12.2917 22.2163 12.2917 22.0018C12.2917 21.7873 12.3769 21.5815 12.5286 21.4298C12.6803 21.2782 12.886 21.1929 13.1005 21.1929L28.9902 21.1929L22.2489 14.7709C22.0998 14.6216 22.015 14.42 22.0125 14.209C22.01 13.9981 22.09 13.7945 22.2355 13.6417C22.381 13.4889 22.5804 13.399 22.7912 13.3912C23.002 13.3833 23.2076 13.4582 23.364 13.5997L31.3659 21.221C31.5407 21.3874 31.6547 21.6077 31.6895 21.8465C31.708 21.9496 31.7077 22.0552 31.6884 22.1581C31.6533 22.3966 31.5394 22.6164 31.3649 22.7826L23.364 30.4028Z" fill="white" />
                                        </svg>
                                    </a>
                                </div>
                            </div>
                        </div>
                        <div class="affiliate_programm__tab--content_right">
                            <div class="swiper programm_slider" data-slider="1">
                                <div class="swiper-wrapper">

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/programm_slide_mob_1.jpg" alt="Download & register the app">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/programm_slide_mob_2.jpg" alt="Starting work">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/programm_slide_mob_3.jpg" alt="Example work basics">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/programm_slide_mob_4.jpg" alt="Statistic & tracking your work">
                                        </div>
                                    </div>

                                    <!-- slide item -->
                                    <div class="swiper-slide">
                                        <div class="programm_image">
                                            <img src="../../assets/images/programm_slide_mob_5.jpg" alt="Payment to you">
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>